insert into mvp.countries (id, sortname, name, phonecode, slug)
values  (1, 'AF', 'Afghanistan', 93, 'afghanistan'),
        (2, 'AL', 'Albania', 355, 'albania'),
        (3, 'DZ', 'Algeria', 213, 'algeria'),
        (4, 'AS', 'American Samoa', 1684, 'american-samoa'),
        (5, 'AD', 'Andorra', 376, 'andorra'),
        (6, 'AO', 'Angola', 244, 'angola'),
        (7, 'AI', 'Anguilla', 1264, 'anguilla'),
        (8, 'AQ', 'Antarctica', 0, 'antarctica'),
        (9, 'AG', 'Antigua And Barbuda', 1268, 'antigua-and-barbuda'),
        (10, 'AR', 'Argentina', 54, 'argentina'),
        (11, 'AM', 'Armenia', 374, 'armenia'),
        (12, 'AW', 'Aruba', 297, 'aruba'),
        (13, 'AU', 'Australia', 61, 'australia'),
        (14, 'AT', 'Austria', 43, 'austria'),
        (15, 'AZ', 'Azerbaijan', 994, 'azerbaijan'),
        (16, 'BS', 'Bahamas The', 1242, 'bahamas-the'),
        (17, 'BH', 'Bahrain', 973, 'bahrain'),
        (18, 'BD', 'Bangladesh', 880, 'bangladesh'),
        (19, 'BB', 'Barbados', 1246, 'barbados'),
        (20, 'BY', 'Belarus', 375, 'belarus'),
        (21, 'BE', 'Belgium', 32, 'belgium'),
        (22, 'BZ', 'Belize', 501, 'belize'),
        (23, 'BJ', 'Benin', 229, 'benin'),
        (24, 'BM', 'Bermuda', 1441, 'bermuda'),
        (25, 'BT', 'Bhutan', 975, 'bhutan'),
        (26, 'BO', 'Bolivia', 591, 'bolivia'),
        (27, 'BA', 'Bosnia and Herzegovina', 387, 'bosnia-and-herzegovina'),
        (28, 'BW', 'Botswana', 267, 'botswana'),
        (29, 'BV', 'Bouvet Island', 0, 'bouvet-island'),
        (30, 'BR', 'Brazil', 55, 'brazil'),
        (31, 'IO', 'British Indian Ocean Territory', 246, 'british-indian-ocean-territory'),
        (32, 'BN', 'Brunei', 673, 'brunei'),
        (33, 'BG', 'Bulgaria', 359, 'bulgaria'),
        (34, 'BF', 'Burkina Faso', 226, 'burkina-faso'),
        (35, 'BI', 'Burundi', 257, 'burundi'),
        (36, 'KH', 'Cambodia', 855, 'cambodia'),
        (37, 'CM', 'Cameroon', 237, 'cameroon'),
        (38, 'CA', 'Canada', 1, 'canada'),
        (39, 'CV', 'Cape Verde', 238, 'cape-verde'),
        (40, 'KY', 'Cayman Islands', 1345, 'cayman-islands'),
        (41, 'CF', 'Central African Republic', 236, 'central-african-republic'),
        (42, 'TD', 'Chad', 235, 'chad'),
        (43, 'CL', 'Chile', 56, 'chile'),
        (44, 'CN', 'China', 86, 'china'),
        (45, 'CX', 'Christmas Island', 61, 'christmas-island'),
        (46, 'CC', 'Cocos (Keeling) Islands', 672, 'cocos-(keeling)-islands'),
        (47, 'CO', 'Colombia', 57, 'colombia'),
        (48, 'KM', 'Comoros', 269, 'comoros'),
        (49, 'CG', 'Republic Of The Congo', 242, 'republic-of-the-congo'),
        (50, 'CD', 'Democratic Republic Of The Congo', 242, 'democratic-republic-of-the-congo'),
        (51, 'CK', 'Cook Islands', 682, 'cook-islands'),
        (52, 'CR', 'Costa Rica', 506, 'costa-rica'),
        (53, 'CI', 'Cote D''Ivoire (Ivory Coast)', 225, 'cote-d''ivoire-(ivory-coast)'),
        (54, 'HR', 'Croatia (Hrvatska)', 385, 'croatia-(hrvatska)'),
        (55, 'CU', 'Cuba', 53, 'cuba'),
        (56, 'CY', 'Cyprus', 357, 'cyprus'),
        (57, 'CZ', 'Czech Republic', 420, 'czech-republic'),
        (58, 'DK', 'Denmark', 45, 'denmark'),
        (59, 'DJ', 'Djibouti', 253, 'djibouti'),
        (60, 'DM', 'Dominica', 1767, 'dominica'),
        (61, 'DO', 'Dominican Republic', 1809, 'dominican-republic'),
        (62, 'TP', 'East Timor', 670, 'east-timor'),
        (63, 'EC', 'Ecuador', 593, 'ecuador'),
        (64, 'EG', 'Egypt', 20, 'egypt'),
        (65, 'SV', 'El Salvador', 503, 'el-salvador'),
        (66, 'GQ', 'Equatorial Guinea', 240, 'equatorial-guinea'),
        (67, 'ER', 'Eritrea', 291, 'eritrea'),
        (68, 'EE', 'Estonia', 372, 'estonia'),
        (69, 'ET', 'Ethiopia', 251, 'ethiopia'),
        (70, 'XA', 'External Territories of Australia', 61, 'external-territories-of-australia'),
        (71, 'FK', 'Falkland Islands', 500, 'falkland-islands'),
        (72, 'FO', 'Faroe Islands', 298, 'faroe-islands'),
        (73, 'FJ', 'Fiji Islands', 679, 'fiji-islands'),
        (74, 'FI', 'Finland', 358, 'finland'),
        (75, 'FR', 'France', 33, 'france'),
        (76, 'GF', 'French Guiana', 594, 'french-guiana'),
        (77, 'PF', 'French Polynesia', 689, 'french-polynesia'),
        (78, 'TF', 'French Southern Territories', 0, 'french-southern-territories'),
        (79, 'GA', 'Gabon', 241, 'gabon'),
        (80, 'GM', 'Gambia The', 220, 'gambia-the'),
        (81, 'GE', 'Georgia', 995, 'georgia'),
        (82, 'DE', 'Germany', 49, 'germany'),
        (83, 'GH', 'Ghana', 233, 'ghana'),
        (84, 'GI', 'Gibraltar', 350, 'gibraltar'),
        (85, 'GR', 'Greece', 30, 'greece'),
        (86, 'GL', 'Greenland', 299, 'greenland'),
        (87, 'GD', 'Grenada', 1473, 'grenada'),
        (88, 'GP', 'Guadeloupe', 590, 'guadeloupe'),
        (89, 'GU', 'Guam', 1671, 'guam'),
        (90, 'GT', 'Guatemala', 502, 'guatemala'),
        (91, 'XU', 'Guernsey and Alderney', 44, 'guernsey-and-alderney'),
        (92, 'GN', 'Guinea', 224, 'guinea'),
        (93, 'GW', 'Guinea-Bissau', 245, 'guinea-bissau'),
        (94, 'GY', 'Guyana', 592, 'guyana'),
        (95, 'HT', 'Haiti', 509, 'haiti'),
        (96, 'HM', 'Heard and McDonald Islands', 0, 'heard-and-mcdonald-islands'),
        (97, 'HN', 'Honduras', 504, 'honduras'),
        (98, 'HK', 'Hong Kong S.A.R.', 852, 'hong-kong-s.a.r.'),
        (99, 'HU', 'Hungary', 36, 'hungary'),
        (100, 'IS', 'Iceland', 354, 'iceland'),
        (101, 'IN', 'India', 91, 'india'),
        (102, 'ID', 'Indonesia', 62, 'indonesia'),
        (103, 'IR', 'Iran', 98, 'iran'),
        (104, 'IQ', 'Iraq', 964, 'iraq'),
        (105, 'IE', 'Ireland', 353, 'ireland'),
        (106, 'IL', 'Israel', 972, 'israel'),
        (107, 'IT', 'Italy', 39, 'italy'),
        (108, 'JM', 'Jamaica', 1876, 'jamaica'),
        (109, 'JP', 'Japan', 81, 'japan'),
        (110, 'XJ', 'Jersey', 44, 'jersey'),
        (111, 'JO', 'Jordan', 962, 'jordan'),
        (112, 'KZ', 'Kazakhstan', 7, 'kazakhstan'),
        (113, 'KE', 'Kenya', 254, 'kenya'),
        (114, 'KI', 'Kiribati', 686, 'kiribati'),
        (115, 'KP', 'Korea North', 850, 'korea-north'),
        (116, 'KR', 'Korea South', 82, 'korea-south'),
        (117, 'KW', 'Kuwait', 965, 'kuwait'),
        (118, 'KG', 'Kyrgyzstan', 996, 'kyrgyzstan'),
        (119, 'LA', 'Laos', 856, 'laos'),
        (120, 'LV', 'Latvia', 371, 'latvia'),
        (121, 'LB', 'Lebanon', 961, 'lebanon'),
        (122, 'LS', 'Lesotho', 266, 'lesotho'),
        (123, 'LR', 'Liberia', 231, 'liberia'),
        (124, 'LY', 'Libya', 218, 'libya'),
        (125, 'LI', 'Liechtenstein', 423, 'liechtenstein'),
        (126, 'LT', 'Lithuania', 370, 'lithuania'),
        (127, 'LU', 'Luxembourg', 352, 'luxembourg'),
        (128, 'MO', 'Macau S.A.R.', 853, 'macau-s.a.r.'),
        (129, 'MK', 'Macedonia', 389, 'macedonia'),
        (130, 'MG', 'Madagascar', 261, 'madagascar'),
        (131, 'MW', 'Malawi', 265, 'malawi'),
        (132, 'MY', 'Malaysia', 60, 'malaysia'),
        (133, 'MV', 'Maldives', 960, 'maldives'),
        (134, 'ML', 'Mali', 223, 'mali'),
        (135, 'MT', 'Malta', 356, 'malta'),
        (136, 'XM', 'Man (Isle of)', 44, 'man-(isle-of)'),
        (137, 'MH', 'Marshall Islands', 692, 'marshall-islands'),
        (138, 'MQ', 'Martinique', 596, 'martinique'),
        (139, 'MR', 'Mauritania', 222, 'mauritania'),
        (140, 'MU', 'Mauritius', 230, 'mauritius'),
        (141, 'YT', 'Mayotte', 269, 'mayotte'),
        (142, 'MX', 'Mexico', 52, 'mexico'),
        (143, 'FM', 'Micronesia', 691, 'micronesia'),
        (144, 'MD', 'Moldova', 373, 'moldova'),
        (145, 'MC', 'Monaco', 377, 'monaco'),
        (146, 'MN', 'Mongolia', 976, 'mongolia'),
        (147, 'MS', 'Montserrat', 1664, 'montserrat'),
        (148, 'MA', 'Morocco', 212, 'morocco'),
        (149, 'MZ', 'Mozambique', 258, 'mozambique'),
        (150, 'MM', 'Myanmar', 95, 'myanmar'),
        (151, 'NA', 'Namibia', 264, 'namibia'),
        (152, 'NR', 'Nauru', 674, 'nauru'),
        (153, 'NP', 'Nepal', 977, 'nepal'),
        (154, 'AN', 'Netherlands Antilles', 599, 'netherlands-antilles'),
        (155, 'NL', 'Netherlands The', 31, 'netherlands-the'),
        (156, 'NC', 'New Caledonia', 687, 'new-caledonia'),
        (157, 'NZ', 'New Zealand', 64, 'new-zealand'),
        (158, 'NI', 'Nicaragua', 505, 'nicaragua'),
        (159, 'NE', 'Niger', 227, 'niger'),
        (160, 'NG', 'Nigeria', 234, 'nigeria'),
        (161, 'NU', 'Niue', 683, 'niue'),
        (162, 'NF', 'Norfolk Island', 672, 'norfolk-island'),
        (163, 'MP', 'Northern Mariana Islands', 1670, 'northern-mariana-islands'),
        (164, 'NO', 'Norway', 47, 'norway'),
        (165, 'OM', 'Oman', 968, 'oman'),
        (166, 'PK', 'Pakistan', 92, 'pakistan'),
        (167, 'PW', 'Palau', 680, 'palau'),
        (168, 'PS', 'Palestinian Territory Occupied', 970, 'palestinian-territory-occupied'),
        (169, 'PA', 'Panama', 507, 'panama'),
        (170, 'PG', 'Papua new Guinea', 675, 'papua-new-guinea'),
        (171, 'PY', 'Paraguay', 595, 'paraguay'),
        (172, 'PE', 'Peru', 51, 'peru'),
        (173, 'PH', 'Philippines', 63, 'philippines'),
        (174, 'PN', 'Pitcairn Island', 0, 'pitcairn-island'),
        (175, 'PL', 'Poland', 48, 'poland'),
        (176, 'PT', 'Portugal', 351, 'portugal'),
        (177, 'PR', 'Puerto Rico', 1787, 'puerto-rico'),
        (178, 'QA', 'Qatar', 974, 'qatar'),
        (179, 'RE', 'Reunion', 262, 'reunion'),
        (180, 'RO', 'Romania', 40, 'romania'),
        (181, 'RU', 'Russia', 70, 'russia'),
        (182, 'RW', 'Rwanda', 250, 'rwanda'),
        (183, 'SH', 'Saint Helena', 290, 'saint-helena'),
        (184, 'KN', 'Saint Kitts And Nevis', 1869, 'saint-kitts-and-nevis'),
        (185, 'LC', 'Saint Lucia', 1758, 'saint-lucia'),
        (186, 'PM', 'Saint Pierre and Miquelon', 508, 'saint-pierre-and-miquelon'),
        (187, 'VC', 'Saint Vincent And The Grenadines', 1784, 'saint-vincent-and-the-grenadines'),
        (188, 'WS', 'Samoa', 684, 'samoa'),
        (189, 'SM', 'San Marino', 378, 'san-marino'),
        (190, 'ST', 'Sao Tome and Principe', 239, 'sao-tome-and-principe'),
        (191, 'SA', 'Saudi Arabia', 966, 'saudi-arabia'),
        (192, 'SN', 'Senegal', 221, 'senegal'),
        (193, 'RS', 'Serbia', 381, 'serbia'),
        (194, 'SC', 'Seychelles', 248, 'seychelles'),
        (195, 'SL', 'Sierra Leone', 232, 'sierra-leone'),
        (196, 'SG', 'Singapore', 65, 'singapore'),
        (197, 'SK', 'Slovakia', 421, 'slovakia'),
        (198, 'SI', 'Slovenia', 386, 'slovenia'),
        (199, 'XG', 'Smaller Territories of the UK', 44, 'smaller-territories-of-the-uk'),
        (200, 'SB', 'Solomon Islands', 677, 'solomon-islands'),
        (201, 'SO', 'Somalia', 252, 'somalia'),
        (202, 'ZA', 'South Africa', 27, 'south-africa'),
        (203, 'GS', 'South Georgia', 0, 'south-georgia'),
        (204, 'SS', 'South Sudan', 211, 'south-sudan'),
        (205, 'ES', 'Spain', 34, 'spain'),
        (206, 'LK', 'Sri Lanka', 94, 'sri-lanka'),
        (207, 'SD', 'Sudan', 249, 'sudan'),
        (208, 'SR', 'Suriname', 597, 'suriname'),
        (209, 'SJ', 'Svalbard And Jan Mayen Islands', 47, 'svalbard-and-jan-mayen-islands'),
        (210, 'SZ', 'Swaziland', 268, 'swaziland'),
        (211, 'SE', 'Sweden', 46, 'sweden'),
        (212, 'CH', 'Switzerland', 41, 'switzerland'),
        (213, 'SY', 'Syria', 963, 'syria'),
        (214, 'TW', 'Taiwan', 886, 'taiwan'),
        (215, 'TJ', 'Tajikistan', 992, 'tajikistan'),
        (216, 'TZ', 'Tanzania', 255, 'tanzania'),
        (217, 'TH', 'Thailand', 66, 'thailand'),
        (218, 'TG', 'Togo', 228, 'togo'),
        (219, 'TK', 'Tokelau', 690, 'tokelau'),
        (220, 'TO', 'Tonga', 676, 'tonga'),
        (221, 'TT', 'Trinidad And Tobago', 1868, 'trinidad-and-tobago'),
        (222, 'TN', 'Tunisia', 216, 'tunisia'),
        (223, 'TR', 'Turkey', 90, 'turkey'),
        (224, 'TM', 'Turkmenistan', 7370, 'turkmenistan'),
        (225, 'TC', 'Turks And Caicos Islands', 1649, 'turks-and-caicos-islands'),
        (226, 'TV', 'Tuvalu', 688, 'tuvalu'),
        (227, 'UG', 'Uganda', 256, 'uganda'),
        (228, 'UA', 'Ukraine', 380, 'ukraine'),
        (229, 'AE', 'United Arab Emirates', 971, 'united-arab-emirates'),
        (230, 'GB', 'United Kingdom', 44, 'united-kingdom'),
        (231, 'US', 'United States', 1, 'united-states'),
        (232, 'UM', 'United States Minor Outlying Islands', 1, 'united-states-minor-outlying-islands'),
        (233, 'UY', 'Uruguay', 598, 'uruguay'),
        (234, 'UZ', 'Uzbekistan', 998, 'uzbekistan'),
        (235, 'VU', 'Vanuatu', 678, 'vanuatu'),
        (236, 'VA', 'Vatican City State (Holy See)', 39, 'vatican-city-state-(holy-see)'),
        (237, 'VE', 'Venezuela', 58, 'venezuela'),
        (238, 'VN', 'Vietnam', 84, 'vietnam'),
        (239, 'VG', 'Virgin Islands (British)', 1284, 'virgin-islands-(british)'),
        (240, 'VI', 'Virgin Islands (US)', 1340, 'virgin-islands-(us)'),
        (241, 'WF', 'Wallis And Futuna Islands', 681, 'wallis-and-futuna-islands'),
        (242, 'EH', 'Western Sahara', 212, 'western-sahara'),
        (243, 'YE', 'Yemen', 967, 'yemen'),
        (244, 'YU', 'Yugoslavia', 38, 'yugoslavia'),
        (245, 'ZM', 'Zambia', 260, 'zambia'),
        (246, 'ZW', 'Zimbabwe', 263, 'zimbabwe');